import Head from "next/head";

const BASE_URL = process.env.NEXT_PUBLIC_VERCEL_URL ?? "http://localhost:3000";

export default function Home() {
  const title = "【カテゴリー】タイトル";
  const userName = "Pandashark";
  const date = new Date();
  const postDate = new Intl.DateTimeFormat("ja").format(date);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta property="og:image" content={`${BASE_URL}/api/og`} />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <img src={`${BASE_URL}/api/og?title=${title}&userName=${userName}&postDate=${postDate}`} alt="" />
    </>
  );
}
